name: Build LaTeX PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # This is mainly done twice because LaTex only outputs TOC on two runs. The first run reads, the second compiles.
      - name: First LaTeX Pass
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode

      - name: Second LaTeX Pass
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode

      - name: Move and Rename PDF (non-fatal)
        run: mv main.pdf document.pdf

      - name: Commit and Push PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add document.pdf
          git commit -m "📄 Generated PDF" || echo "No changes to commit"
          git push
